### ISSUE TITLE
0.2.1 Fails to install

### ISSUE THREAD

**Issue by sonnyp** [dodo/node-tls-connect#1]
No problem with 
`npm install tls-connect@0.2.0`
but
`npm install tls-connect`
fails:

```
➜  repo git:(master) ✗ npm install tls-connect
npm http GET https://registry.npmjs.org/tls-connect
npm http 304 https://registry.npmjs.org/tls-connect
npm http GET https://registry.npmjs.org/tls-connect/-/tls-connect-0.2.1.tgz
npm http 404 https://registry.npmjs.org/tls-connect/-/tls-connect-0.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/tls-connect/-/tls-connect-0.2.1.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "install" "tls-connect"
npm ERR! cwd /Users/sonny/Projects/yuilop/happy/repo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/sonny/Projects/yuilop/happy/repo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by dodo** [comment]
problem is already tracked at node-xmpp/node-xmpp-core#27

**Comment by dodo** [comment]
fixed.
